apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: {{ .Values.description | quote }}
    openshift.io/display-name: {{ .Values.displayName | quote }}
    openshift.io/requester: {{ .Values.requester }}
    scheduler.alpha.kubernetes.io/node-selector: {{ .Values.nodeSelector }}
  name: {{ .Values.name }}
spec:
  finalizers:
    - kubernetes
