apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: {{ .Values.name }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: admin
subjects:
- kind: User
  name: {{ .Values.admin }}
userNames:
- {{ .Values.admin }}
