apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: {{ .Values.name }}
roleRef:
  name: admin
  apiGroup: authorization.openshift.io
subjects:
- kind: User
  name: {{ .Values.admin }}
userNames:
- {{ .Values.admin }}
