apiVersion: v1
kind: Namespace
metadata:
    annotations:
        openshift.io/description: ""
        openshift.io/display-name: ""
        openshift.io/requester: admin@nikio.io
    name: demo3
spec:
    finalizers:
        - kubernetes
